//
//  NearByCars_Router.swift
//  IBM_POC
//
//  Created by Darshan on 04/05/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol NearByCars_RoutingLogic {
}

protocol NearByCars_DataPassing {
  var dataStore: NearByCars_DataStore? { get }
}

class NearByCars_Router: NSObject, NearByCars_RoutingLogic, NearByCars_DataPassing {
    
  weak var viewController: NearByCars_ViewController?
  var dataStore: NearByCars_DataStore?
}
