//
//  NearByCars_Presenter.swift
//  IBM_POC
//
//  Created by Darshan on 04/05/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NearByCars_PresentationLogic {
  func presentNearByCars(response: NearByCars_.Fetch.Response)
}

class NearByCars_Presenter: NearByCars_PresentationLogic {
    
  weak var viewController: NearByCars_DisplayLogic?
  
  func presentNearByCars(response: NearByCars_.Fetch.Response)
  {
    // Create view model to holde response
    let viewModel = NearByCars_.Fetch.ViewModel(nearByCarModel: response.nearByCarModel)
    viewController?.displayNearByCars(viewModel: viewModel)
  }
}
