//
//  NearByCars_Interactor.swift
//  IBM_POC
//
//  Created by Darshan on 04/05/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NearByCars_BusinessLogic {
  func fetchNearByCars(request: NearByCars_.Fetch.Request)
}

protocol NearByCars_DataStore {
  var nearByCars: [NearByCarModel]! { get set }
}

class NearByCars_Interactor: NearByCars_BusinessLogic, NearByCars_DataStore {
    
  var presenter: NearByCars_PresentationLogic?
  var worker: NearByCars_Worker?
  var nearByCars: [NearByCarModel]!
  
  // MARK: Do something
    
  init() {
        worker = NearByCars_Worker()
    }
  
  func fetchNearByCars(request: NearByCars_.Fetch.Request) {
    // Trigger api call in worker
    worker?.fetchNearByCars()
  }
}

extension NearByCars_Interactor: NearByCars_WorkerOutput {
    
    func fetchedCarList(model: [NearByCarModel]) {
        // Store model further feature development
        nearByCars = model
        // Create response to list of cars
        let response = NearByCars_.Fetch.Response(nearByCarModel: model)
        presenter?.presentNearByCars(response: response)
    }
}
